import "../../styles/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Heading from "../components/Heading/Heading";
import Movie from "../components/Movie/Movie";
import MovieCard from "../components/MovieCard/MovieCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie List",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }) {
  return (
    <>
    {/* <Head></Head> is a built in component, that allows you to modify the HTML <Head /> element. 
    It is where you define metadata, link stylesheets, include external scripts and set other various configurations in our HTML doc. */}
      <Head>
        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={metadata.description} />
      </Head>
    <Heading />
    <Movie />
    </>
  );
}
